name: Analyze Code

on: 
  pull_request:
  
  workflow_dispatch:

jobs:
  format-check:
    name: Lint Code Base with Prettier 
    runs-on: windows-2022
    timeout-minutes: 60

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run format
  JS:
    name: Lint JS Files 
    runs-on: windows-2022
    timeout-minutes: 60

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install packages
        run: npm ci
      - name: Lint JavaScript files 
        run: npm run lintJS
  HTML:
      name: Lint HTML Files 
      runs-on: windows-2022
      timeout-minutes: 60

      steps:

        - name: Checkout Code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Install packages
          run: npm ci
        - name: Lint HTML files 
          run: npm run lintHTML
  CSS:
      name: Lint CSS Files 
      runs-on: windows-2022
      timeout-minutes: 60

      steps:

        - name: Checkout Code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Install packages
          run: npm ci
        - name: Lint CSS files 
          run: npm run lintCSS
