name: Run Tests

on: 
    pull_request:
        
    workflow_dispatch:
    
jobs:
    jest-test:
        timeout-minutes: 60
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [windows-latest]
                node-version: [14.x, 16.x, 18.x, 20.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install
              run: |
                  npm install
            - name: test
              run: |
                  npm test --findRelatedTests tests/unit/
                  
                  
    playwright-test:
        timeout-minutes: 60
        runs-on:  ${{ matrix.os }}
        
        strategy:
            matrix:
                os: [windows-latest]
                node-version: [14.x, 16.x, 18.x, 20.x]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm install
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run Playwright tests
              run: npx playwright test tests/acceptance --pass-with-no-tests
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                name: playwright-report
                path: playwright-report/
                retention-days: 30
