name: Lint Code Base

on: 
  pull_request:
        branches: [ main ]
  workflow_dispatch:

jobs:
  linter:
    name: Lint Code Base
    runs-on: ${{ matrix.os }}
    
    strategy:
            matrix:
                os: [windows-2022]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install packages
        run: npm ci
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
